### ISSUE TITLE
Order By

### ISSUE THREAD

**Issue by jmcgaha** [the-refinery/relatedentriesautomation#1]
The order by functionality doesn't seem to be working properly.

Look at the events list on this page:
https://www.lynn.edu/resources/alumni

This field is set to order on Expiry Date (screenshot for full setup is below).

If I output the following tag, the order is correct:
`craft.relatedentriesautomation.buildEnityQuery(block.sourceCriteria)`

However, we normally wrap that with a craft.entries tag to be able to loop through all the fields. But this query overwrites the order and instead orders by postDate.
`craft.entries(craft.relatedentriesautomation.buildEnityQuery(block.sourceCriteria))`

Is there any way we can get a twig variable or something so that we could specify what the sort order would be in the craft.entries query? Something like this:

`craft.entries(craft.relatedentriesautomation.buildEnityQuery(block.sourceCriteria)).orderBy(block.sourceCriteria.orderBy)`

<img width="447" alt="screen shot 2018-09-28 at 4 34 57 pm" src="https://user-images.githubusercontent.com/49672/46232370-00e18080-c33d-11e8-9073-c6d173aaa0fc.png">

**Comment by criticalmash** [comment]
Jon have you tried inspecting `block.sourceCriteria`? Everything `buildEnityQuery()` needs should be inside that object, including the sort order.

Just checked the docs for craft 3 and see that there is a `fixedorder` parameter.
https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#fixedorder
Using that should return items in the same order as returned by `buildEnityQuery()`

Let me know if you need more assistance.

**Comment by jmcgaha** [comment]
fixedOrder() worked perfectly. I never knew that parameter existed.

Thanks!
