### ISSUE TITLE
Page-breaking error when searching on title

### ISSUE THREAD

**Issue by jmcgaha** [the-refinery/relatedentriesautomation#2]
This page is down currently (but we'll probably disable the affected block to get it back up):
https://www.lynn.edu/career-connections

I have it tracked to a query from this plugin. Attached is the screenshot.
If I remove the part searching on the title, it works, so it appears to be something there.

Let me know if you need any more info.

<img width="468" alt="screen shot 2018-10-05 at 3 11 45 pm" src="https://user-images.githubusercontent.com/49672/46555611-d8fc9a80-c8b1-11e8-89f2-6ed77fbb35a9.png">

1. in /Users/jonathanmcgaha/Sites/TheRefinery/lynn-craft/vendor/therefinery/relatedentriesautomation/src/services/EntriesFilterService.php at line 163
154155156157158159160161162163164165166167168169170171172                     
        foreach ($entryParams as $query) {
            $attributes = Craft::$app->sections->getEntryTypesByHandle($query['handle'])[0]->getAttributes();
            $clause = "`typeId` = {$attributes['id']}";
            $relations = array();
 
            if (isset($query['params'])) {
                foreach ($query['params'] as $param) {
                    $field = Craft::$app->fields->getFieldByHandle($param['handle']);
                    $fieldId = $field->id;
                    $fieldName = 'field_' . $param['handle'];
                    if($param['handle'] === 'title' OR $param['handle'] === 'postDate'){
                        $fieldName = $param['handle'];
                    }
                    $value = $param['value'];
                    if($param['operator'] === 'LIKE'){
                        $value = "%".$value.'%';
                        $clause .= " AND {{%content}}.{$fieldName} {$param['operator']} '{$value}' ";
                    }
                
2. in /Users/jonathanmcgaha/Sites/TheRefinery/lynn-craft/vendor/therefinery/relatedentriesautomation/src/services/EntriesFilterService.php at line 80 – therefinery\relatedentriesautomation\services\EntriesFilterService::whereClause()
74757677787980818283848586                            // additional WHERE clause for each entryType
        if (isset($criteria['entryTypes']) && count($criteria['entryTypes'])) {
            // $typeIds = $this->entityQueryWithIds($entryTypes)['id'];
            // $entriesQuery->andWhere(
            //  array('IN', 'typeId', $typeIds)
            // );
            $where = join(' OR ', $this->whereClause($criteria['entryTypes']));
            $this->entriesQuery->andWhere($where);
        }
 
        $result = $this->entriesQuery->all();
        $query = $this->entriesQuery->getRawSql();

**Comment by criticalmash** [comment]
Is this being recreated on staging? I'd like to test it there and take a closer look.

**Comment by jmcgaha** [comment]
Yes, happening there as well.
http://3.staging.lynn.edu/career-connections

**Comment by criticalmash** [comment]
I think this is related to Title not being a proper field (it's actually a column in the entry table) the same error occurs for Post Date. I'll wrap that line in an `else` clause and we should be OK.

**Comment by criticalmash** [comment]
Just pushed a fix to master. You should be good now.

**Comment by jmcgaha** [comment]
That worked. Thanks John.
